onboarding = false

[keys]
prefix = "ctrl+s"
split_horizontal = "prefix+minus"
split_vertical = "prefix+|"
last_pane = "prefix+l"

[theme]
name = "rose-pine"
auto_switch = false

[ui.toast]
delivery = "herdr"

[ui]
show_agent_labels_on_pane_borders = true

[[keys.command]]
key = "prefix+o"
type = "shell"
command = "herdr pane split --pane \"$HERDR_ACTIVE_PANE_ID\" --direction right --ratio 0.75 --focus"
description = "open narrow right pane"

# --- Switch workspaces
[[keys.command]]
key = "prefix+!"
type = "shell"
command = "herdr workspace focus 1"
description = "switch to workspace 1"

[[keys.command]]
key = "prefix+@"
type = "shell"
command = "herdr workspace focus 2"
description = "switch to workspace 2"

[[keys.command]]
key = "prefix+#"
type = "shell"
command = "herdr workspace focus 3"
description = "switch to workspace 3"

[[keys.command]]
key = "prefix+$"
type = "shell"
command = "herdr workspace focus 4"
description = "switch to workspace 4"

[[keys.command]]
key = "prefix+%"
type = "shell"
command = "herdr workspace focus 5"
description = "switch to workspace 5"

[[keys.command]]
key = "prefix+^"
type = "shell"
command = "herdr workspace focus 6"
description = "switch to workspace 6"

[[keys.command]]
key = "prefix+&"
type = "shell"
command = "herdr workspace focus 7"
description = "switch to workspace 7"

[[keys.command]]
key = "prefix+*"
type = "shell"
command = "herdr workspace focus 8"
description = "switch to workspace 8"

[[keys.command]]
key = "prefix+("
type = "shell"
command = "herdr workspace focus 9"
description = "switch to workspace 9"

# --- https://github.com/lmilojevicc/herdr-splits.nvim
[[keys.command]]
key = "ctrl+h"
type = "plugin_action"
command = "herdr-splits.nav-left"

[[keys.command]]
key = "ctrl+j"
type = "plugin_action"
command = "herdr-splits.nav-down"

[[keys.command]]
key = "ctrl+k"
type = "plugin_action"
command = "herdr-splits.nav-up"

[[keys.command]]
key = "ctrl+l"
type = "plugin_action"
command = "herdr-splits.nav-right"

[[keys.command]]
key = "alt+h"
type = "plugin_action"
command = "herdr-splits.resize-left"

[[keys.command]]
key = "alt+j"
type = "plugin_action"
command = "herdr-splits.resize-down"

[[keys.command]]
key = "alt+k"
type = "plugin_action"
command = "herdr-splits.resize-up"

[[keys.command]]
key = "alt+l"
type = "plugin_action"
command = "herdr-splits.resize-right"
