# [bootstrap.packages]
# "brew:jj" = "latest"
# # GUI apps
# "brew-cask:spotify" = "latest"
# "brew-cask:itsycal" = "latest"

[tools]
claude-code = "latest"
codex = "latest"
tree-sitter = "latest"
# rust
rust-analyzer = "latest" # keep ahead of rust in PATH
rust = "stable"
# lua
lua-language-server = "latest"
stylua = "latest"
# erlang / elixir
erlang = "latest"
elixir = "latest"
"aqua:remoteoss/dexter" = "latest"
# js / node
node = "latest"
pnpm = "latest"
"npm:typescript" = "latest"
